### ISSUE TITLE
Problem when using object data as options

### ISSUE THREAD

**Issue by AdamGerthel** [tamtakoe/oi.select#69]
I'm trying to use oi.select with an object as options, using the key as option value and the object value as option label. The reason for that is basically that that's how my data is formatted. The issue is that the selected values are not properly stored. My code works for ngOptions, but not for oi.select.

I've made a plunkr to demonstrate: http://plnkr.co/edit/Yvty2csdZ3yDBhLhvd5c?p=preview

Maybe I've completely misunderstood the docs, and maybe it's just not possible to use key/values of an object to populate the options with, but since the readme refers to ngOptions for how to use the oi-options directive, I figured I'd create an issue here.

**Comment by lesliemklo** [comment]
+1

**Comment by tamtakoe** [comment]
It fixed in v. 0.2.21

**Comment by mataps** [comment]
I can confirm this is not fixed on 0.2.21 also track by syntax not working
